import { ISong } from '../../types';

export const SONGS = [
  {
    id: 1,
    singerId: [1, 2],
    name: 'smack that',
    playbackTime: 206,
  },
  {
    id: 2,
    singerId: [2],
    name: 'lonely',
    playbackTime: 235,
  },
  {
    id: 3,
    singerId: [2],
    name: 'bananza',
    playbackTime: 238,
  },
  {
    id: 4,
    singerId: [2],
    name: 'keep you much longer',
    playbackTime: 238,
  },
  {
    id: 5,
    singerId: [3],
    name: 'believer',
    playbackTime: 205,
  },
  {
    id: 6,
    singerId: [3],
    name: 'bones',
    playbackTime: 166,
  },
  {
    id: 7,
    singerId: [3],
    name: 'thunder',
    playbackTime: 188,
  },
  {
    id: 8,
    singerId: [3],
    name: 'natural',
    playbackTime: 190,
  },
  {
    id: 9,
    singerId: [3],
    name: 'demons',
    playbackTime: 178,
  },
  {
    id: 10,
    singerId: [3],
    name: 'sharks',
    playbackTime: 191,
  },
  {
    id: 11,
    singerId: [3, 4, 5],
    name: 'sucker for pain',
    playbackTime: 244,
  },
  {
    id: 12,
    singerId: [5, 6],
    name: 'young, wild & free',
    playbackTime: 207,
  },
  {
    id: 13,
    singerId: [5],
    name: 'see you again',
    playbackTime: 230,
  },
  {
    id: 14,
    singerId: [5],
    name: 'black and yellow',
    playbackTime: 218,
  },
  {
    id: 15,
    singerId: [7],
    name: 'good old-fashioned lover',
    playbackTime: 173,
  },
  {
    id: 16,
    singerId: [7],
    name: 'another one bites the dust',
    playbackTime: 214,
  },
  {
    id: 17,
    singerId: [7],
    name: 'the show must go one',
    playbackTime: 277,
  },
  {
    id: 18,
    singerId: [7],
    name: 'we will rock you',
    playbackTime: 122,
  },
  {
    id: 19,
    singerId: [8],
    name: 'style',
    playbackTime: 230,
  },
  {
    id: 20,
    singerId: [8, 9],
    name: 'everything has changed',
    playbackTime: 244,
  },
  {
    id: 21,
    singerId: [8, 9, 10],
    name: 'end game',
    playbackTime: 245,
  },
  {
    id: 22,
    singerId: [9],
    name: 'shape of you',
    playbackTime: 234,
  },
  {
    id: 23,
    singerId: [9, 11],
    name: 'i don`t care',
    playbackTime: 234,
  },
  {
    id: 24,
    singerId: [9, 14],
    name: 'peru',
    playbackTime: 188,
  },
  {
    id: 25,
    singerId: [9],
    name: '2step',
    playbackTime: 154,
  },
  {
    id: 26,
    singerId: [8],
    name: 'shake it off',
    playbackTime: 239,
  },
  {
    id: 27,
    singerId: ['taylor swift'],
    name: 'love story',
    playbackTime: 235,
  },
  {
    id: 28,
    singerId: [11],
    name: 'ghost',
    playbackTime: 155,
  },
  {
    id: 29,
    singerId: [11, 12],
    name: 'bad guy',
    playbackTime: 195,
  },
  {
    id: 30,
    singerId: [11],
    name: 'love yourself',
    playbackTime: 244,
  },
  {
    id: 31,
    singerId: ['justin bieber'],
    name: 'sorry',
    playbackTime: 321,
  },
  {
    id: 32,
    singerId: [12],
    name: 'lovely',
    playbackTime: 201,
  },
  {
    id: 33,
    singerId: [12],
    name: 'bored',
    playbackTime: 180,
  },
  {
    id: 34,
    singerId: [12],
    name: 'no time to die',
    playbackTime: 180,
  },
  {
    id: 35,
    singerId: [13],
    name: 'fever',
    playbackTime: 157,
  },
  {
    id: 36,
    singerId: [13],
    name: 'one kiss',
    playbackTime: 215,
  },
  {
    id: 37,
    singerId: [13],
    name: 'love again',
    playbackTime: 338,
  },
  {
    id: 38,
    singerId: [13],
    name: 'break my heart',
    playbackTime: 338,
  },
  {
    id: 39,
    singerId: [1],
    name: 'rap god',
    playbackTime: 363,
  },
  {
    id: 40,
    singerId: [1],
    name: 'sing for the moment',
    playbackTime: 339,
  },
] as ISong[];
